<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>code.as</string>
		<key>fileTypes</key>
		<array>
			<string>as</string>
		</array>
		<key>name</key>
		<string>AS file</string>
		<key>patterns</key>
		<array>
			<dict>
				<!-- Quoted strings with " -->
				<key>match</key>
				<string>"(.*?)"</string>
				<key>name</key>
				<string>string.quoted</string>
			</dict>
			<dict>
				<!-- Quoted strings with ' -->
				<key>match</key>
				<string>'(.*?)'</string>
				<key>name</key>
				<string>string.quoted</string>
			</dict>
			<dict>
				<!-- Comment -->
				<key>match</key>
				<string>;.*</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>
			<dict>
				<!-- Numeric (decimal) -->
				<key>match</key>
				<string>\b\d+\.?\d*?\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<!-- Numeric (hex) -->
				<key>match</key>
				<string>\b(?i:(0?x)?[0-9a-f][0-9a-f]+)\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<!-- Numeric (boolean) -->
				<key>match</key>
				<string>\b(?i:(high|HIGH|low|LOW|on|ON|off|OFF))(\:|\b)</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<!-- Numeric (boolean) -->
				<key>match</key>
				<string>\b(?i:(high|IF|END|THEN|ELSE))(\:|\b)</string>
				<key>name</key>
				<string>punctuation.definition.group.regexp</string>
			</dict>
			<dict>
				<!-- Robot Commands -->
				<key>match</key>
				<string>\b(?i:(ACCURACY|LINEAR|JOINT|SPEED|ACCEL|DECEL|QTOOL|TOOL|PRINT))(\:|\b)</string>
				<key>name</key>
				<string>entity.name.class</string>
			</dict>
			<dict>
				<!-- Robot Commands -->
				<key>match</key>
				<string>\b(?i:(HERE|LMOVE|JMOVE|POINT|JAPPRO))(\:|\b)</string>
				<key>name</key>
				<string>keyword</string>
			</dict>
			<dict>
				<!-- Robot Commands2 -->
				<key>match</key>
				<string>\b(?i:(BREAK|HALT|RETURN|PAUSE))(\:|\b)</string>
				<key>name</key>
				<string>token.warn-token</string>
			</dict>
			<dict>
				<!-- Robot Commands3 -->
				<key>match</key>
				<string>\b(?i:(SIGNAL|WAIT))(\:|\b)</string>
				<key>name</key>
				<string>constant.character.escape</string>
			</dict>
			<dict>
				<!-- Robot Programs -->
				<key>match</key>
				<string>\.PROGRAM.*</string>
				<key>name</key>
				<string>entity.name.function</string>
			</dict>
			<dict>
				<!-- Robot Programs -->
				<key>match</key>
				<string>\.END</string>
				<key>name</key>
				<string>entity.name.function</string>
			</dict>
			<dict>
				<!-- Robot Commands4 -->
				<key>match</key>
				<string>\b(?i:(GOTO))(\:|\b)</string>
				<key>name</key>
				<string>constant.character</string>
			</dict>
			<dict>
				<!-- Program label in GOTO -->
				<key>match</key>
				<string>GOTO (.*)</string>
				<key>name</key>
				<string>keyword.control</string>
			</dict>
			<dict>
				<!-- Program label -->
				<key>match</key>
				<string>\w*:</string>
				<key>name</key>
				<string>keyword.control</string>
			</dict>
		</array>
		<key>uuid</key>
		<string>ab259404-3072-4cd4-a943-7cbbd32e373f</string>
	</dict>
</plist>